/*
Deployment script for C:\USERS\KRAK\DESKTOP\ASP.NET\SHAREPOINT-SCHOOL\PORTAL AUKCYJNY\PORTAL AUKCYJNY\APP_DATA\PORTALAUKCYJNY.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "C:\USERS\KRAK\DESKTOP\ASP.NET\SHAREPOINT-SCHOOL\PORTAL AUKCYJNY\PORTAL AUKCYJNY\APP_DATA\PORTALAUKCYJNY.MDF"
:setvar DefaultFilePrefix "C_\USERS\KRAK\DESKTOP\ASP.NET\SHAREPOINT-SCHOOL\PORTAL AUKCYJNY\PORTAL AUKCYJNY\APP_DATA\PORTALAUKCYJNY.MDF_"
:setvar DefaultDataPath "C:\Users\krak\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\krak\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Dropping [dbo].[fk_auctions]...';


GO
ALTER TABLE [dbo].[Auctions] DROP CONSTRAINT [fk_auctions];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Dropping [dbo].[fk_categories]...';


GO
ALTER TABLE [dbo].[Auctions] DROP CONSTRAINT [fk_categories];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Dropping [dbo].[fk_shipments]...';


GO
ALTER TABLE [dbo].[Auctions] DROP CONSTRAINT [fk_shipments];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Dropping [dbo].[fk_bids]...';


GO
ALTER TABLE [dbo].[Bidders] DROP CONSTRAINT [fk_bids];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Dropping [dbo].[fk_comments]...';


GO
ALTER TABLE [dbo].[Comments] DROP CONSTRAINT [fk_comments];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Dropping [dbo].[fk_watched_auctions]...';


GO
ALTER TABLE [dbo].[Observers] DROP CONSTRAINT [fk_watched_auctions];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
/*
The type for column Image in table [dbo].[Auctions] is currently  NVARCHAR (MAX) NOT NULL but is being changed to  IMAGE NULL. Data loss could occur.
*/
GO
PRINT N'Starting rebuilding table [dbo].[Auctions]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Auctions] (
    [Id]            INT              IDENTITY (1, 1) NOT NULL,
    [Title]         NVARCHAR (MAX)   NOT NULL,
    [Description]   NVARCHAR (MAX)   NOT NULL,
    [Image]         IMAGE            NULL,
    [BuyItNowPrice] DECIMAL (18)     NOT NULL,
    [Location]      NVARCHAR (MAX)   NOT NULL,
    [OwnerId]       UNIQUEIDENTIFIER NOT NULL,
    [ShipmentId]    INT              NOT NULL,
    [CategoryId]    INT              NOT NULL,
    [Views]         INT              NOT NULL,
    [EndDate]       DATETIME         NOT NULL,
    [Finalized]     BIT              NOT NULL,
    [ItemsNumber]   INT              NOT NULL,
    [BuyItNow]      BIT              NOT NULL,
    [Auction]       BIT              NOT NULL,
    [CurrentPrice]  DECIMAL (18)     NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Auctions])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Auctions] ON;
        INSERT INTO [dbo].[tmp_ms_xx_Auctions] ([Id], [Title], [Description], NULL, [BuyItNowPrice], [Location], [OwnerId], [ShipmentId], [CategoryId], [Views], [EndDate], [Finalized], [ItemsNumber], [BuyItNow], [Auction], [CurrentPrice])
        SELECT   [Id],
                 [Title],
                 [Description],
                 [Image],
                 [BuyItNowPrice],
                 [Location],
                 [OwnerId],
                 [ShipmentId],
                 [CategoryId],
                 [Views],
                 [EndDate],
                 [Finalized],
                 [ItemsNumber],
                 [BuyItNow],
                 [Auction],
                 [CurrentPrice]
        FROM     [dbo].[Auctions]
        ORDER BY [Id] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Auctions] OFF;
    END

DROP TABLE [dbo].[Auctions];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Auctions]', N'Auctions';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[fk_auctions]...';


GO
ALTER TABLE [dbo].[Auctions] WITH NOCHECK
    ADD CONSTRAINT [fk_auctions] FOREIGN KEY ([OwnerId]) REFERENCES [dbo].[aspnet_Users] ([UserId]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[fk_categories]...';


GO
ALTER TABLE [dbo].[Auctions] WITH NOCHECK
    ADD CONSTRAINT [fk_categories] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[Categories] ([Id]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[fk_shipments]...';


GO
ALTER TABLE [dbo].[Auctions] WITH NOCHECK
    ADD CONSTRAINT [fk_shipments] FOREIGN KEY ([ShipmentId]) REFERENCES [dbo].[Shipments] ([Id]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[fk_bids]...';


GO
ALTER TABLE [dbo].[Bidders] WITH NOCHECK
    ADD CONSTRAINT [fk_bids] FOREIGN KEY ([AuctionId]) REFERENCES [dbo].[Auctions] ([Id]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[fk_comments]...';


GO
ALTER TABLE [dbo].[Comments] WITH NOCHECK
    ADD CONSTRAINT [fk_comments] FOREIGN KEY ([AuctionId]) REFERENCES [dbo].[Auctions] ([Id]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[fk_watched_auctions]...';


GO
ALTER TABLE [dbo].[Observers] WITH NOCHECK
    ADD CONSTRAINT [fk_watched_auctions] FOREIGN KEY ([AuctionId]) REFERENCES [dbo].[Auctions] ([Id]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[Auctions] WITH CHECK CHECK CONSTRAINT [fk_auctions];

ALTER TABLE [dbo].[Auctions] WITH CHECK CHECK CONSTRAINT [fk_categories];

ALTER TABLE [dbo].[Auctions] WITH CHECK CHECK CONSTRAINT [fk_shipments];

ALTER TABLE [dbo].[Bidders] WITH CHECK CHECK CONSTRAINT [fk_bids];

ALTER TABLE [dbo].[Comments] WITH CHECK CHECK CONSTRAINT [fk_comments];

ALTER TABLE [dbo].[Observers] WITH CHECK CHECK CONSTRAINT [fk_watched_auctions];


GO
PRINT N'Update complete.';


GO
