//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_aukcyjny
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auctions
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int OwnerId { get; set; }
        public string ImageUrl { get; set; }
        public string Location { get; set; }
        public decimal BuyItNowPrice { get; set; }
        public decimal CurrentPrice { get; set; }
        public System.DateTime EndDate { get; set; }
        public int BiddersNum { get; set; }
        public int Visits { get; set; }
        public int ShipmentId { get; set; }
        public string Category_1 { get; set; }
        public string Category_2 { get; set; }
    }
}
