//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_aukcyjny
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auctions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auctions()
        {
            this.Bidders = new HashSet<Bidders>();
            this.Comments = new HashSet<Comments>();
            this.Observers = new HashSet<Observers>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public decimal BuyItNowPrice { get; set; }
        public string Location { get; set; }
        public System.Guid OwnerId { get; set; }
        public int ShipmentId { get; set; }
        public int CategoryId { get; set; }
        public int Views { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool Finalized { get; set; }
        public int ItemsNumber { get; set; }
        public bool BuyItNow { get; set; }
        public bool Auction { get; set; }
        public decimal CurrentPrice { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bidders> Bidders { get; set; }
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual Shipments Shipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Observers> Observers { get; set; }
    }
}
