//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int Id { get; set; }
        public string Comment { get; set; }
        public Nullable<int> AuctionId { get; set; }
        public System.Guid AuthorId { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid RecipientId { get; set; }
        public bool AuthorIsSeller { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Auctions Auctions { get; set; }
    }
}
